In [1]:
#decision tree
import pandas as pd
import numpy as np

In [30]:
train=pd.read_csv("data/titanic/train.csv")
test=pd.read_csv("data/titanic/test.csv")

In [31]:
train.describe()
train.isnull().sum()
print(train['Age'].mean())

29.69911764705882

In [32]:
train['Age_mean']=train['Age']
train['Age_mean'].fillna(train['Age_mean'].mean(),inplace=True)
test['Age_mean']=test['Age']
test['Age_mean'].fillna(test['Age_mean'].mean(),inplace=True)

In [33]:
train['Age_mean'].isnull().sum()

0

In [34]:
train['Age_mean'].mean() #29.69
#print(train['Age'].mean())

29.699117647058763

In [35]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [36]:
train['Gender']=(train['Sex']=='female')
test['Gender']=(test['Sex']=='female')

In [37]:
train['Embarked'].value_counts()
train['Embarked'].isnull().sum() #2

2

In [38]:
print(test['Embarked'].isnull().sum())

0

In [40]:
train['Embarked_S']=train['Embarked']=='S'
train['Embarked_C']=train['Embarked']=='C'
train['Embarked_Q']=train['Embarked']=='Q'
#S:100, C:010, Q:001

In [42]:
train['Embarked'].value_counts()
train['Embarked_S'].sum()

644

In [43]:
train[['Embarked_S','Embarked_C','Embarked_Q']]

     Embarked_S  Embarked_C  Embarked_Q
0          True       False       False
1         False        True       False
2          True       False       False
3          True       False       False
4          True       False       False
5         False       False        True
6          True       False       False
7          True       False       False
8          True       False       False
9         False        True       False
10         True       False       False
11         True       False       False
12         True       False       False
13         True       False       False
14         True       False       False
15         True       False       False
16        False       False        True
17         True       False       False
18         True       False       False
19        False        True       False
20         True       False       False
21         True       False       False
22        False       False        True
23         True       False       False
24         True       False       False
25         True       False       False
26        False        True       False
27         True       False       False
28        False       False        True
29         True       False       False
..          ...         ...         ...
861        True       False       False
862        True       False       False
863        True       False       False
864        True       False       False
865        True       False       False
866       False        True       False
867        True       False       False
868        True       False       False
869        True       False       False
870        True       False       False
871        True       False       False
872        True       False       False
873        True       False       False
874       False        True       False
875       False        True       False
876        True       False       False
877        True       False       False
878        True       False       False
879       False        True       False
880        True       False       False
881        True       False       False
882        True       False       False
883        True       False       False
884        True       False       False
885       False       False        True
886        True       False       False
887        True       False       False
888        True       False       False
889       False        True       False
890       False       False        True

[891 rows x 3 columns]

In [44]:
test['Embarked_S']=test['Embarked']=='S'
test['Embarked_C']=test['Embarked']=='C'
test['Embarked_Q']=test['Embarked']=='Q'

In [50]:
train['FamilySize']=train['SibSp']+train['Parch']+1
train['FamilySize'].value_counts()
train['Family']=train['FamilySize']
#대가족(5이상):L, 소가족(1):S, 중가족(2~4):M

train.loc[train['FamilySize']==1,'Family']='S'
train.loc[(train['FamilySize']>1) & (train['FamilySize']<5),'Family']='M'
train.loc[train['FamilySize']>4,'Family']='L'
train[['Family', 'FamilySize']]

    Family  FamilySize
0        M           2
1        M           2
2        S           1
3        M           2
4        S           1
5        S           1
6        S           1
7        L           5
8        M           3
9        M           2
10       M           3
11       S           1
12       S           1
13       L           7
14       S           1
15       S           1
16       L           6
17       S           1
18       M           2
19       S           1
20       S           1
21       S           1
22       S           1
23       S           1
24       L           5
25       L           7
26       S           1
27       L           6
28       S           1
29       S           1
..     ...         ...
861      M           2
862      S           1
863      L          11
864      S           1
865      S           1
866      M           2
867      S           1
868      S           1
869      M           3
870      S           1
871      M           3
872      S           1
873      S           1
874      M           2
875      S           1
876      S           1
877      S           1
878      S           1
879      M           2
880      M           2
881      S           1
882      S           1
883      S           1
884      S           1
885      L           6
886      S           1
887      S           1
888      M           4
889      S           1
890      S           1

[891 rows x 2 columns]

In [51]:
train['Family_S']=train['Family']=='S'
train['Family_M']=train['Family']=='M'
train['Family_L']=train['Family']=='L'

In [52]:
train[['Family_S', 'Family_M','Family_L','Family',
       'FamilySize']]

     Family_S  Family_M  Family_L Family  FamilySize
0       False      True     False      M           2
1       False      True     False      M           2
2        True     False     False      S           1
3       False      True     False      M           2
4        True     False     False      S           1
5        True     False     False      S           1
6        True     False     False      S           1
7       False     False      True      L           5
8       False      True     False      M           3
9       False      True     False      M           2
10      False      True     False      M           3
11       True     False     False      S           1
12       True     False     False      S           1
13      False     False      True      L           7
14       True     False     False      S           1
15       True     False     False      S           1
16      False     False      True      L           6
17       True     False     False      S           1
18      False      True     False      M           2
19       True     False     False      S           1
20       True     False     False      S           1
21       True     False     False      S           1
22       True     False     False      S           1
23       True     False     False      S           1
24      False     False      True      L           5
25      False     False      True      L           7
26       True     False     False      S           1
27      False     False      True      L           6
28       True     False     False      S           1
29       True     False     False      S           1
..        ...       ...       ...    ...         ...
861     False      True     False      M           2
862      True     False     False      S           1
863     False     False      True      L          11
864      True     False     False      S           1
865      True     False     False      S           1
866     False      True     False      M           2
867      True     False     False      S           1
868      True     False     False      S           1
869     False      True     False      M           3
870      True     False     False      S           1
871     False      True     False      M           3
872      True     False     False      S           1
873      True     False     False      S           1
874     False      True     False      M           2
875      True     False     False      S           1
876      True     False     False      S           1
877      True     False     False      S           1
878      True     False     False      S           1
879     False      True     False      M           2
880     False      True     False      M           2
881      True     False     False      S           1
882      True     False     False      S           1
883      True     False     False      S           1
884      True     False     False      S           1
885     False     False      True      L           6
886      True     False     False      S           1
887      True     False     False      S           1
888     False      True     False      M           4
889      True     False     False      S           1
890      True     False     False      S           1

[891 rows x 5 columns]

In [53]:
test['FamilySize']=test['SibSp']+test['Parch']+1
test['FamilySize'].value_counts()
test['Family']=test['FamilySize']
#대가족(5이상):L, 소가족(1):S, 중가족(2~4):M

test.loc[train['FamilySize']==1,'Family']='S'
test.loc[(train['FamilySize']>1) & (test['FamilySize']<5),'Family']='M'
test.loc[train['FamilySize']>4,'Family']='L'
test[['Family', 'FamilySize']]

    Family  FamilySize
0        M           1
1        M           2
2        S           1
3        M           1
4        S           3
5        S           1
6        S           1
7        L           3
8        M           1
9        M           3
10       M           1
11       S           1
12       S           2
13       L           2
14       S           2
15       S           2
16       L           1
17       S           1
18       M           2
19       S           1
20       S           2
21       S           2
22       S           1
23       S           2
24       L           5
25       L           2
26       S           2
27       L           1
28       S           1
29       S           3
..     ...         ...
388      S           1
389      S           5
390      M           1
391      S           2
392      M           3
393      M           1
394      5           5
395      S           2
396      S           1
397      S           3
398      S           1
399      S           1
400      S           1
401      S           2
402      M           2
403      M           1
404      S           2
405      M           1
406      S           2
407      M           3
408      S           1
409      L           3
410      S           1
411      S           2
412      M           1
413      S           1
414      S           1
415      S           1
416      M           1
417      M           3

[418 rows x 2 columns]

In [55]:
test['Family_S']=test['Family']=='S'
test['Family_M']=test['Family']=='M'
test['Family_L']=test['Family']=='L'

In [56]:
test[['Family_S', 'Family_M','Family_L','Family',
       'FamilySize']]

     Family_S  Family_M  Family_L Family  FamilySize
0       False      True     False      M           1
1       False      True     False      M           2
2        True     False     False      S           1
3       False      True     False      M           1
4        True     False     False      S           3
5        True     False     False      S           1
6        True     False     False      S           1
7       False     False      True      L           3
8       False      True     False      M           1
9       False      True     False      M           3
10      False      True     False      M           1
11       True     False     False      S           1
12       True     False     False      S           2
13      False     False      True      L           2
14       True     False     False      S           2
15       True     False     False      S           2
16      False     False      True      L           1
17       True     False     False      S           1
18      False      True     False      M           2
19       True     False     False      S           1
20       True     False     False      S           2
21       True     False     False      S           2
22       True     False     False      S           1
23       True     False     False      S           2
24      False     False      True      L           5
25      False     False      True      L           2
26       True     False     False      S           2
27      False     False      True      L           1
28       True     False     False      S           1
29       True     False     False      S           3
..        ...       ...       ...    ...         ...
388      True     False     False      S           1
389      True     False     False      S           5
390     False      True     False      M           1
391      True     False     False      S           2
392     False      True     False      M           3
393     False      True     False      M           1
394     False     False     False      5           5
395      True     False     False      S           2
396      True     False     False      S           1
397      True     False     False      S           3
398      True     False     False      S           1
399      True     False     False      S           1
400      True     False     False      S           1
401      True     False     False      S           2
402     False      True     False      M           2
403     False      True     False      M           1
404      True     False     False      S           2
405     False      True     False      M           1
406      True     False     False      S           2
407     False      True     False      M           3
408      True     False     False      S           1
409     False     False      True      L           3
410      True     False     False      S           1
411      True     False     False      S           2
412     False      True     False      M           1
413      True     False     False      S           1
414      True     False     False      S           1
415      True     False     False      S           1
416     False      True     False      M           1
417     False      True     False      M           3

[418 rows x 5 columns]

In [59]:
train['Family'].value_counts()
#test['Family'].value_counts()

S    537
M    292
L     62
Name: Family, dtype: int64

In [61]:
train.head()
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,Age_mean,Gender,Embarked_S,Embarked_C,Embarked_Q,FamilySize,Family,Family_S,Family_M,Family_L
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,...,34.5,False,False,False,True,1,M,False,True,False
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,...,47.0,True,True,False,False,2,M,False,True,False
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,...,62.0,False,False,False,True,1,S,True,False,False
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,...,27.0,False,True,False,False,1,M,False,True,False
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,...,22.0,True,True,False,False,3,S,True,False,False

In [62]:
train['Pclass'].dtypes

dtype('int64')

In [63]:
train['Pclass']=train['Pclass'].astype('category')
train['Pclass'].dtypes

CategoricalDtype(categories=[1, 2, 3], ordered=False)

In [69]:
fn=['Gender', 'Age_mean', 'Embarked_S', 'Embarked_C', 
    'Embarked_Q', 'Family_S', 'Family_M', 'Family_L']
#train.info()
X_train=train[fn]
X_train.head()
y_label=train['Survived']
X_test=test[fn]

In [94]:
#모델링(디시전 트리)
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=3)
model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [95]:
model.fit(X_train, y_label)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [96]:
from sklearn.model_selection import KFold, cross_val_score
kfold=KFold(n_splits=10, shuffle=True, random_state=2019)#n_splits=3, random_state=None, shuffle=False
kfold

KFold(n_splits=10, random_state=2019, shuffle=True)

In [97]:
score=cross_val_score(model, X_train, y_label, 
                      cv=kfold, scoring='accuracy')
print(score)
np.mean(score)

[0.85555556 0.79775281 0.84269663 0.84269663 0.80898876 0.85393258
 0.74157303 0.80898876 0.83146067 0.79775281]

0.8181398252184768

In [98]:
prediction=model.predict(X_test)
prediction.shape

(418,)

In [99]:
test['Survived']=prediction
test.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'Age_mean', 'Gender',
       'Embarked_S', 'Embarked_C', 'Embarked_Q', 'FamilySize', 'Family',
       'Family_S', 'Family_M', 'Family_L', 'Survived'],
      dtype='object')

In [101]:
submission=test[['PassengerId','Survived']]
submission.to_csv("submit.csv", index=False)

In [102]:
import urllib.request
url="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
sname="test.png"
urllib.request.urlretrieve(url, sname)
print("저장됐습니다")

저장됐습니다

In [105]:
#urlopen()함수는 메모리 저장
import urllib.request
url="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
sname="test2.png"
mem=urllib.request.urlopen(url).read() #메모리저장
with open(sname, mode="wb") as f:
    f.write(mem)
    print("이미지가 또 저장됐습니다")

이미지가 또 저장됐습니다

In [ ]:
#www.kma.go.kr/weather/forecast/mid-term-rss3.jsp
#웹 문서 형식 : json, html(비구조 문서=>해석(기계가) 어려움), 
#xml(구조화된 문서=>기계가 해석 가능), rdf, ...

In [115]:
import urllib.parse
values={'stnId':'184'} #제주도
#www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?'stnId':'184'
params=urllib.parse.urlencode(values)
API="http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
url=API+"?"+params
data=urllib.request.urlopen(url).read()
text=data.decode('utf-8')
print(text)

<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0">
<channel>
<title>기상청 육상 중기예보</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_07.jsp</link>
<description>기상청 날씨 웹서비스</description>
<language>ko</language>
<generator>기상청</generator>
<pubDate>2019년 07월 16일 (화)요일 06:00</pubDate>
 <item>
<author>기상청</author>
<category>육상중기예보</category>
<title>제주도 육상 중기예보 - 2019년 07월 16일 (화)요일 06:00 발표</title>
<link>http://www.kma.go.kr/weather/forecast/mid-term_07.jsp</link>
<guid>http://www.kma.go.kr/weather/forecast/mid-term_07.jsp</guid>
<description>
	<header>
		<title>제주도 육상중기예보</title>
		<tm>201907160600</tm>
		<wf><![CDATA[19일에 장마전선의 영향으로 비가 오겠고, 그 밖의 날은 고기압 가장자리에 들어 구름이 많겠습니다.<br />기온은 평년(최저기온: 24~25℃, 최고기온: 29~30℃)과 비슷하겠습니다. 강수량은 평년(4~10mm)보다 많겠습니다.<br />바다의 물결은 제주도전해상과 남해서부먼바다에서 19~21일에 1.0~4.0m로 높게 일고, 그 밖의 날은 1.0~2.0m로 일겠습니다.<br /><br />* 열대저압부(TD)의 발달 여부와 북태평양고기압의 확장 정도에 따라 장마전선의 위치와 강수 영역이 달라질 수 있으니, 앞으로 발표되는 기상정보를 참고하기 바랍니다.]]></wf>
	</header>
	<body>


		<location wl_ver="3">
				<province>제주도</province>
				<city>제주</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>26</tmn>
					<tmx>31</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>26</tmn>
					<tmx>31</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>26</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>26</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>31</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>31</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>31</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>서귀포</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>성산</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>25</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>성판악</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>18</tmn>
					<tmx>23</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>18</tmn>
					<tmx>23</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>20</tmn>
					<tmx>25</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>20</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>26</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>26</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>24</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>24</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>26</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>26</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>19</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>고산</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>30</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>이어도</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>24</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>24</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>24</tmn>
					<tmx>25</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>

		<location wl_ver="3">
				<province>제주도</province>
				<city>추자도</city>

				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 00:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>70</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-19 12:00</tmEf>
					<wf>흐리고 비</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>낮음</reliability>
					<rnSt>60</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>27</tmx>
					<reliability>낮음</reliability>
					<rnSt>40</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-20 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>27</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-21 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>27</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-22 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>27</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>22</tmn>
					<tmx>27</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A02</mode>
					<tmEf>2019-07-23 12:00</tmEf>
					<wf>구름많음</wf>
					<tmn>22</tmn>
					<tmx>27</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-24 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>28</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-25 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


				<data>
					<mode>A01</mode>
					<tmEf>2019-07-26 00:00</tmEf>
					<wf>구름많음</wf>
					<tmn>23</tmn>
					<tmx>29</tmx>
					<reliability>보통</reliability>
					<rnSt>30</rnSt>
				</data>


		</location>




	</body>
</description>
</item>
</channel>
</rss>

In [129]:
from bs4 import BeautifulSoup
html="""
<html>
<body>
<h1>멀티캠퍼스</h1>
<h1>역삼동</h1>
<p>1003호</p>
<p>빅데이터 설계반</p>
</body>
</html>
"""
soup=BeautifulSoup(html,'html.parser')
#soup.html.body.h1.string
#soup.h1
#soup.html.body.p.string
p1=soup.html.body.p
p1.next_sibling.next_sibling

#api referenece:www.crummy.com/software/BeautifulSoup/bs4/doc

In [ ]:
# urllib:url을 다루는 모듈의 집합
# urllib.request:웹 데이터 접근
# 쿠키,세션

In [139]:
#id로 요소를 추출
html="""
<html><body>
<h1 id="title">스크래핑?</h1>
<p>웹 페이지 분석</p>
<p id="myid">원하는 부분 추출</p>
</body></html>
"""
#html 분석
soup=BeautifulSoup(html, 'html5lib')
title=soup.find(id='title')
myid=soup.find(id='myid')
print(title.string)
print(myid.string)
print(soup.find("p").string)

스크래핑?
원하는 부분 추출
웹 페이지 분석

In [151]:
#find_all()를 이용한 여러 요소 추출
html="""
<html><body>
<ul>
<li><a href="http://www.naver.com">naver</a></li>
<li><a href="http://www.daum.net">daum</a></li>
</ul>
</body></html>
"""
soup=BeautifulSoup(html, 'html.parser')
links=soup.find_all("a")
# for link in links:
#     href=link.attrs['href']    
#     text=link.string
#     print(text, " ===> ",href)
for link in links:
    href=link.get('href')
    text=link.string
    print(text, " ===> ",href)

naver  ===>  http://www.naver.com
daum  ===>  http://www.daum.net

In [155]:

#기상청으로 이동해서
#1.title태그 내용 추출
#2.wf태그 내용 추출
#3.tmn, tmx 값 추출
# =>카페 게시판 코드 업로드

In [ ]:
#css선택자 : jQuery처럼, css선택자 사용가능. 특정 요소 추출
#soup.select(<선택자>):여러개 요소
#soup.select_one(<선택자>):1개 요소

In [170]:
html="""
<html><body>
<h1>역삼동</h1>
<div id="myid">
<h1>멀티캠퍼스</h1>
<ul class="items">
<li>강의실</li>
<li>엘레베이터</li>
<li>식당</li>
</ul>
</div></body></html>
"""
soup=BeautifulSoup(html, 'html.parser')

soup.select("div#myid ul.items li")
#print(soup.select("li"))

# print(soup.select_one("div#myid h1").string)
# print(soup.select_one("div#myid > h1"))

# print(soup.select_one("h1"))
# print(soup.select_one("li"))
# print(soup.select("li"))