In [53]:
import pandas as pd
import seaborn as sns
tips = sns.load_dataset("tips")

In [54]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [25]:

type(tips)

pandas.core.frame.DataFrame

In [33]:
tips['sex']=tips['sex'].astype('str')

In [34]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null object
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(3), float64(2), int64(1), object(1)
memory usage: 8.8+ KB

In [55]:
tips.loc[[1,3,5,7],'tip']='missing'
tips

     total_bill      tip     sex smoker   day    time  size
0         16.99     1.01  Female     No   Sun  Dinner     2
1         10.34  missing    Male     No   Sun  Dinner     3
2         21.01      3.5    Male     No   Sun  Dinner     3
3         23.68  missing    Male     No   Sun  Dinner     2
4         24.59     3.61  Female     No   Sun  Dinner     4
5         25.29  missing    Male     No   Sun  Dinner     4
6          8.77        2    Male     No   Sun  Dinner     2
7         26.88  missing    Male     No   Sun  Dinner     4
8         15.04     1.96    Male     No   Sun  Dinner     2
9         14.78     3.23    Male     No   Sun  Dinner     2
10        10.27     1.71    Male     No   Sun  Dinner     2
11        35.26        5  Female     No   Sun  Dinner     4
12        15.42     1.57    Male     No   Sun  Dinner     2
13        18.43        3    Male     No   Sun  Dinner     4
14        14.83     3.02  Female     No   Sun  Dinner     2
15        21.58     3.92    Male     No   Sun  Dinner     2
16        10.33     1.67  Female     No   Sun  Dinner     3
17        16.29     3.71    Male     No   Sun  Dinner     3
18        16.97      3.5  Female     No   Sun  Dinner     3
19        20.65     3.35    Male     No   Sat  Dinner     3
20        17.92     4.08    Male     No   Sat  Dinner     2
21        20.29     2.75  Female     No   Sat  Dinner     2
22        15.77     2.23  Female     No   Sat  Dinner     2
23        39.42     7.58    Male     No   Sat  Dinner     4
24        19.82     3.18    Male     No   Sat  Dinner     2
25        17.81     2.34    Male     No   Sat  Dinner     4
26        13.37        2    Male     No   Sat  Dinner     2
27        12.69        2    Male     No   Sat  Dinner     2
28        21.70      4.3    Male     No   Sat  Dinner     2
29        19.65        3  Female     No   Sat  Dinner     2
..          ...      ...     ...    ...   ...     ...   ...
214       28.17      6.5  Female    Yes   Sat  Dinner     3
215       12.90      1.1  Female    Yes   Sat  Dinner     2
216       28.15        3    Male    Yes   Sat  Dinner     5
217       11.59      1.5    Male    Yes   Sat  Dinner     2
218        7.74     1.44    Male    Yes   Sat  Dinner     2
219       30.14     3.09  Female    Yes   Sat  Dinner     4
220       12.16      2.2    Male    Yes   Fri   Lunch     2
221       13.42     3.48  Female    Yes   Fri   Lunch     2
222        8.58     1.92    Male    Yes   Fri   Lunch     1
223       15.98        3  Female     No   Fri   Lunch     3
224       13.42     1.58    Male    Yes   Fri   Lunch     2
225       16.27      2.5  Female    Yes   Fri   Lunch     2
226       10.09        2  Female    Yes   Fri   Lunch     2
227       20.45        3    Male     No   Sat  Dinner     4
228       13.28     2.72    Male     No   Sat  Dinner     2
229       22.12     2.88  Female    Yes   Sat  Dinner     2
230       24.01        2    Male    Yes   Sat  Dinner     4
231       15.69        3    Male    Yes   Sat  Dinner     3
232       11.61     3.39    Male     No   Sat  Dinner     2
233       10.77     1.47    Male     No   Sat  Dinner     2
234       15.53        3    Male    Yes   Sat  Dinner     2
235       10.07     1.25    Male     No   Sat  Dinner     2
236       12.60        1    Male    Yes   Sat  Dinner     2
237       32.83     1.17    Male    Yes   Sat  Dinner     2
238       35.83     4.67  Female     No   Sat  Dinner     3
239       29.03     5.92    Male     No   Sat  Dinner     3
240       27.18        2  Female    Yes   Sat  Dinner     2
241       22.67        2    Male    Yes   Sat  Dinner     2
242       17.82     1.75    Male     No   Sat  Dinner     2
243       18.78        3  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [57]:
 gapminder=pd.read_csv('data/gapminder.tsv', sep='\t')

In [61]:
gapminder.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

[Scikitlearn을 활용한 머신러닝]

1. 위 문장을 모두 수행한 후, 아래와 같은 요구사항을 구현하시오.

   1)  tips의 'sex‘ 컬럼의 타입을 문자열로 변환한 다음, info함수를 호출하여 결과를 확인하시오. 

   2) tips의 1,3,5,7번 index행에 저장된 tip 컬럼의 값을 모두 ‘missing'으로 변경하시오

   3) scikitlearn에 있는 preprocessing 모듈중 표준화 및 정규화와 관련된 함수를 모두 기술하시오  

   - `RobustScaler(X)`: 중앙값(median)이 0, IQR(interquartile range)이 1이 되도록 변환.
   - `MinMaxScaler(X)`: 최대값이 각각 1, 최소값이 0이 되도록 변환
   - `MaxAbsScaler(X)`: 0을 기준으로 절대값이 가장 큰 수가 1또는 -1이 되도록 변환
   - `StandardScaler(X)`: 평균이 0과 표준편차가 1이 되도록 변환.

2.  표준화와 정규화의 차이점을 설명하시오. 
    - 표준 편차: 
    각 observation이 평균을 기준으로 어느 정도 떨어져 있는지를 나타낼때 사용된다. 값의 스케일이 다른 두 개의 변수가 있을 때, 이 변수들의 스케일 차이를 제거해 주는 효과가 있다. 제로 평균 으로부터 각 값들의 분산을 나타낸다. 각 요소의 값에서 평균을 뺀 다음 표준편차로 나누어 준다
    - 정규화:
    데이터의 범위를 0과 1로 변환하여 데이터 분포를 조정하는 방법이다.  

3. 데이터 분석을 위해 필요로 하는 라이브러리 및 용도를 기술하시오.

      - Numpy는 과학계산용 패키지로 파이썬의 기본 자료구조보다 빠르고 효율적인 다차원배열 객체 ndarray를 제공합니다.
      또한, 배열 원소를 다루거나 배열간의 수학계산을 수행하는 함수, 선형대수의 계산, 푸리에 변환, 난수 발생기 같은 수치와 관련된 다양한 기능을 제공합니다. SciPy는 수치적분 루틴과 미분방정식 해석기, 방정식의 근을 구하는 알고리즘, 표준 연속/이산 확률분포와 다양한 통계관련 도구 등을 제공합니다.

      - pandas는 의해 개발된 고수준의 자료구조와 파이썬을 통한 빠르고 쉬운 데이터 분석도구를 제공합니다. 
      개발자인 웨스 맥키니는 그의 책에서 아래와 같은 기능을 필요로해서 이 라이브러리를 개발했다고 합니다.그리고 한 가지 언어로 범용 소프트웨어를 쉽게 개발할 수 있도록 이 기능들이 한 번에 해결할 수 있기를 원했다고 합니다.자동적으로 혹은 명시적으로 축의 이름에 따라 데이터를 정렬할 수 있는 자료구조,통합된 시계열 기능, 시계열 데이터와 비시계열 데이터를 함께 다룰 수 있는 통합 자료구조, 누락된 데이터를 유연하게 처리할 수 있는 기능, SQL과 같은 일반 데이터베이스처럼 데이터를 합치고 관계연산을 수행하는 기능, 산술연산과 한 축의 모든 값을 더하는 등의 데이터 축약연산

      - matplotlib은 파이썬에서 그래프나 시각화 표현을 위해 사용되는 매우 중요한 라이브러리입니다.
      출판물에 필요한 수준의 그래프를 만드는 데 초점을 두고 존 D.헌터(John D. Hunter)에 의해 개발되었습니다.

   

   [Azure 머신러닝을 활용한 기계학습]

4. 분산과 공분산의 차이점을 설명하시오.

   1. **평균적인 편차(표준편차)의 제곱**  모든 x값에 대해 x평균과의 차이를 제곱해서 다 더한 다음에 x의 수로 나누면 평균적인 차이의 제곱, 즉 분산이 나온다
   2.  **두 변수간 평균적인 편차의 곱이다.**  0에 가까울수록 공동 변화량이 없는거다. 절대값이 클수록 공동 변화량이 큰거다.

5.  gapminder=pd.read_csv('../data/gapminder.tsv', sep='\t')  위 코드를 수행한 후,  gapmider 변수에 저장된 컬럼 중 'year' 컬럼을 기준으로 'lifeExp' 컬럼값에 대한 평균을 구하고자 한다. 코드를 기술하시오

6.  머신러닝 학습 방법의 종류에 대해 나열하고, 설명하시오
    지도학습(Supervised Learning)
      컴퓨터에게 Feature를 학습하여, 새로운 Feature값을 넣으면 컴퓨터가 계산을 통해서 매매가격을 예측하는 것이다. 이렇게 학습하는 것이 바로 지도학습이다.


    비지도 학습(Unsupervised Learning)

    비지도 학습은 비지도 한다는 말처럼 사람의 개입이 없이 컴퓨터가 알아서 어떠한 결과를 도출해 내는 것을 뜻한다. 지도 학습은 우리가 결과를 안다는 가정하에 컴퓨터가 그에 맞춰서 문제를 해결하는 것을 원한다고 한다면 비지도는 우리도 뭔지 모르는 무언가를 컴퓨터가 해결하길 바라는 것이다.

    강화학습

    강화 학습의 핵심은 바로 보상(Reward)이다. 컴퓨터는 이 보상을 받는 행위를 위해서 스스로 문제점을 찾아나가게 되는데 초반에는 인간의 어느정도의 개입이 들어갈 수 있다. 
지도학습과 비지도학습은 컴퓨터가 스스로 성장하는 모습이 쉽지 않는 모양이지만, 강화학습은 목표가 보상의 최대치가 되는 행동을 하자라는 것이다. 예를 들어, 게임을 한다면 최종스코어(Max Score)를 최대치를 만드는 것이 임무일 수 있고, 이 최대치를 만들기 위해서 끊임없이 노력을 하게 된다. 


7. 그룹화와 관련된 함수 및 형식을 기술하시오.

   1. `groupby` 결과, 즉 `GroupBy` 클래스 객체의 뒤에 붙일 수 있는 그룹연산 메서드는 다양하다. 다음은 자주 사용되는 그룹연산 메서드들이다.

      - `size`, `count`: 그룹 데이터의 갯수
      - `mean`, `median`, `min`, `max`: 그룹 데이터의 평균, 중앙값, 최소, 최대
      - `sum`, `prod`, `std`, `var`, `quantile` : 그룹 데이터의 합계, 곱, 표준편차, 분산, 사분위수
      - `first`, `last`: 그룹 데이터 중 가장 첫번째 데이터와 가장 나중 데이터

      이 외에도 많이 사용되는 것으로는 다음과 같은 그룹연산이 있다.

      - `agg`, `aggregate`
        - 만약 원하는 그룹연산이 없는 경우 함수를 만들고 이 함수를 `agg`에 전달한다.
        - 또는 여러가지 그룹연산을 동시에 하고 싶은 경우 함수 이름 문자열의 리스트를 전달한다.
      - `describe`
        - 하나의 그룹 대표값이 아니라 여러개의 값을 데이터프레임으로 구한다.
      - `apply`
        - `describe` 처럼 하나의 대표값이 아닌 데이터프레임을 출력하지만 원하는 그룹연산이 없는 경우에 사용한다.
      - `transform`
        - 그룹에 대한 대표값을 만드는 것이 아니라 그룹별 계산을 통해 데이터 자체를 변형한다.